### ISSUE TITLE
unexpected input format

### ISSUE THREAD

**Issue by sedrik** [Diksta33/PathOfExileClipboardListener#1]
First of all let me say that I love the idea of this program.

Using the latest release (1.0.0.6) the following gives me a incorrect string format error.

<pre>
Rarity: Rare
Blood Talons
Shagreen Gloves
--------
Evasion Rating: 154
--------
Requirements:
Level: 54 (unmet)
Dex: 78
--------
Sockets: G-G 
--------
Itemlevel: 55
--------
+29 to Dexterity
+44 to maximum Life
2.3 Life Regenerated per second
14% increased Rarity of Items found
</pre>

**Comment by Diksta33** [comment]
![gloves](https://f.cloud.github.com/assets/6487051/2034650/8fd10d36-892e-11e3-9416-90959cb5c821.png)
I just tried those gloves and they worked fine for me.  I will be publishing a new version in the next few hours, it's possibly something I fixed since the last release?

**Comment by sedrik** [comment]
Will try the new version tomorrow then =)

**Comment by sedrik** [comment]
Also this was in collection mode but that should not make a difference.
